######################################################################################
## NOTE: To use the configration for running/removing OpenCms,                      ##
##  - adjust the "volume" entries to fit for your system                            ##
##  - run `docker-compose up -d` in the folder with this file to run all containers ##
##  - run `docker-compose down` in the folder with this file to remove all running  ##
##    containers mentioned in that file                                             ##
##  - If you already had installed a version of OpenCms via this setup, using the   ##
##    same volumes: For a fresh installation, remove the volumes from your system   ##
##    before running `docker-compose up -d`, otherwise the system will only update  ##
##    and also not install the demo modules.                                        ##
######################################################################################

version: '3.7'
services:
    mariadb:
        image: mariadb:latest
        container_name: mariadb
        init: true
        restart: always
        volumes:
            - ~/dockermount/opencms-docker-mysql:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=secretDBpassword"

    opencms:
        image: alkacon/opencms-docker:12.0
        container_name: opencms
        build: ./image
        init: true
        restart: always
        depends_on: [ "mariadb" ]
        links:
            - "mariadb:mysql"
        ports:
            - "80:8080"
        volumes:
            - ~/dockermount/opencms-docker-webapps:/usr/local/tomcat/webapps
        command: ["/root/wait-for.sh", "mysql:3306", "-t", "30", "--", "/root/opencms-run.sh"] # waiting for the mysql container to be ready
        environment:
            - "DB_PASSWD=secretDBpassword" # DB password, same as MYSQL_ROOT_PASSWORD of the mysql/mariadb container
 #           - "GZIP=true"
 #           - "TOMCAT_OPTS=-Xmx2g -Xms512m -server -XX:+UseConcMarkSweepGC"
 #           - "ADMIN_PASSWD=admin" # individual Admin password
 #           - "DB_HOST=mysql"
 #           - "DB_NAME=opencms"
 #           - "OPENCMS_COMPONENTS=workplace,demo"
 #           - "WEBRESOURCES_CACHE_SIZE=200000"
 #           - "DEBUG=false" # Enable debugging