services:
    postgres:
        image: postgres:latest
        container_name: postgres
        init: true
#        restart: always
        volumes:
            - ~/dockermount/opencms-docker-postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=root
            - POSTGRES_USER=root
    opencms:
        image: alkacon/opencms-docker:17.0
        container_name: opencms
        build: ../image
        init: true
#        restart: always
        depends_on: [ "postgres" ]
        ports:
            - "80:8080"
        volumes:
            - ~/dockermount/opencms-docker-webapps:/usr/local/tomcat/webapps
            - ./custom-setup.properties:/custom-setup.properties
        command: ["/root/wait-for.sh", "postgres:5432", "-t", "30", "--", "/root/opencms-run.sh"]
